version: "3.9"

services:
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: snippetbox
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - 3306:3306
        restart: always
        command:
            [
                "mysqld",
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--default-authentication-plugin=mysql_native_password",
            ]

    adminer:
        image: adminer
        environment:
            ADMINER_DESIGN: dracula
        ports:
            - 8888:8080
        restart: always
